Feature/slideshow banner
themoment-team/MontBlanc-front pull request #266
Opened 2021-12-22 09:30 UTC by chanwoo00106

## 개요

> 배너 기능이 추가되어 만들었습니다.

## 작업사항

- 배너 퍼블리싱
- 배너 recoil 생성
- 하루 동안 보지 않기 기능

2021-12-22 09:35 UTC, hyeongrok7874 requested changes

2021-12-22 09:35 UTC, hyeongrok7874 commented on .vscode/settings.json
> +}
불 필요한 파일이 commit 된 것 같습니다~

2021-12-22 09:37 UTC, hyeongrok7874 requested changes

2021-12-22 09:37 UTC, hyeongrok7874 commented on src/Components/Common/Header/index.tsx
> +
테스트를 위한 console.log는 빼는거 좋을 것 같습니다!

2021-12-22 09:50 UTC, sunwoo0706 commented on src/Atom/BannerContainer.ts
> +});
`src/` 디렉토리 하위에 atom을 관리하는 파일이 따로 있습니다. `atom` 특성상 전역적으로 활용할 수 있게 수정이 필요해보이네요.

2021-12-22 09:53 UTC, sunwoo0706 commented on src/Components/Banner/index.tsx
> +  const [_, setShowBanner] = useRecoilState(ShowBanner);
`recoil` 의 set 메써드만 사용할 것이면 [`useSetRecoilState`](https://recoiljs.org/ko/docs/api-reference/core/useSetRecoilState/) 를 사용하는 것이 더 좋겠네요.

2021-12-22 10:17 UTC, sunwoo0706 commented on src/Atom/BannerContainer.ts
> +const showBanner = (): boolean => {
함수 Declaration과 타이핑을 봤을때는 무엇을 하는 함수인지 전혀 모르겠군요.

2021-12-22 10:17 UTC, sunwoo0706 commented on src/Components/Common/Header/index.tsx
> +      {showBanner && <Banner />}
getBannerVisibleState 같은 작명이라던지.. 한번 생각해보세요

2021-12-22 10:19 UTC, sunwoo0706 commented on src/Atom/BannerContainer.ts
> +};
그리고 이 함수는 banner 컴포넌트를 컨디셔널하게 컨트롤하려 만든 함수인것 같은데 hooks 폴더를 만들던지 하여 커스텀 훅으로 따로 빼는것이 좋아보이는군요.

2021-12-22 10:20 UTC, sunwoo0706 commented on src/Components/Banner/index.tsx
> +              style={{ backgroundImage: `url(/slideImg${slide})` }}
`/slideImg/${파일명}` 과 같이 하는것이 더 좋아보이네요.

2021-12-22 10:21 UTC, sunwoo0706 reviewed
이것은 제 의견입니다

2021-12-22 10:21 UTC, sunwoo0706 commented on src/Components/Banner/index.tsx
> +const slideImages = ["/banner.png", "/banner.png", "/banner.png"];
이곳에서 / 를 빼고

2021-12-22 10:21 UTC, sunwoo0706 commented on src/Components/Banner/index.tsx
> +              style={{ backgroundImage: `url(/slideImg${slide})` }}
여기에 붙이는게 더 좋아보입니다.

2021-12-22 10:23 UTC, sunwoo0706 commented on src/Atom/BannerContainer.ts
> +};
어차피 이 밑에 있는 atom은 AtomContainer로 옮겨줘야 하므로

2021-12-22 10:33 UTC, sunwoo0706 commented on src/Atom/BannerContainer.ts
> +});
`atom` 들은 `AtomContainer` 에 넣는걸 원칙으로 하고 있습니다.

2021-12-22 10:34 UTC, sunwoo0706 requested changes

2021-12-22 10:34 UTC, sunwoo0706 commented on src/Atom/BannerContainer.ts
> +});
`atom` 들은 `AtomContainer` 에 넣는걸 원칙으로 하고 있습니다.

2021-12-22 10:35 UTC, chanwoo00106 commented on src/Components/Banner/index.tsx
> +              style={{ backgroundImage: `url(/slideImg${slide})` }}
띄어쓰기 말하시는 건가요?

2021-12-22 10:36 UTC, sunwoo0706 commented on src/Components/Banner/index.tsx
> +              style={{ backgroundImage: `url(/slideImg${slide})` }}
```suggestion
              style={{ backgroundImage: `url(/slideImg/${slide})` }}
```

2021-12-22 10:36 UTC, chanwoo00106 commented on src/Components/Banner/index.tsx
> +const slideImages = ["/banner.png", "/banner.png", "/banner.png"];
/를 빼면 이미지를 불러오지 못해서 이렇게 작성했습니다

2021-12-22 10:37 UTC, sunwoo0706 commented on src/Components/Banner/index.tsx
> +const slideImages = ["/banner.png", "/banner.png", "/banner.png"];
그야 밑에서 / 을 붙여줘야죠

2021-12-22 10:37 UTC, chanwoo00106 commented on src/Components/Banner/index.tsx
> +              style={{ backgroundImage: `url(/slideImg${slide})` }}
아하

2021-12-22 11:43 UTC, sunwoo0706 commented on src/Components/Banner/index.tsx
> +    localStorage.setItem("the-moment-banner", `${date}`);
더불어 date 값을 저장하는데 왜 key 값이 "the-moment-banner" 인가요?
그리고 굳이 localstorage를 써야 할 이유가 있을까요?

2021-12-22 11:45 UTC, sunwoo0706 commented on tsconfig.json
> +    "typeRoots": ["./types", "./node_modules/@types"]
`config` 파일을 수정할때는 pm에게 승인을 받은후 바꿉시다.

2021-12-22 11:47 UTC, sunwoo0706 commented on src/Components/Common/Header/index.tsx
>  import { faBars, faChevronUp } from "@fortawesome/free-solid-svg-icons";
이런식이면 아무도 무슨 svg 키워드인줄 모르므로 as를 사용하여 다른 개발자들이 알기 쉽게 import 해오는것이 좋겠네요

2021-12-22 11:47 UTC, chanwoo00106 commented on src/Components/Banner/index.tsx
> +    localStorage.setItem("the-moment-banner", `${date}`);
하루 동안 보지 않기 기능을 구현하면서 어쩔 수 없이 localstorage를 쓸 수 밖에 없었습니다
그러면서 the-moment-banner라는 이름을 짓게 되었고요
혹시 이 기능을 구현하는데 더 좋은 방법이 있을까요?

2021-12-22 11:49 UTC, sunwoo0706 commented on src/Components/Banner/index.tsx
> +    localStorage.setItem("the-moment-banner", `${date}`);
음음 알겠습니다. `storage` 쓰는게 좋겠네요. 하지만 작명은 바꿀 필요가 있어보입니다.

2021-12-22 11:50 UTC, chanwoo00106 commented on tsconfig.json
> +    "typeRoots": ["./types", "./node_modules/@types"]
react-slideshow-banner를 typescript에서 사용하려면 저 부분을 작성해야 했습니다
상의 없이 수정한 점 죄송합니다

2021-12-22 11:52 UTC, sunwoo0706 commented on src/Components/Banner/index.tsx
> +    localStorage.setItem("the-moment-banner", `${date}`);
보지 않는다를 선택했다는 사실은 페이지를 닫아도 휘발되지 않아야할 정보므로 `web storage` 를 사용하는것이 당연해보입니다.
잘했어요 !
하지만 저처럼 이해하지 못하는 사람이 있을수도 있으니 작명은 변경하는것이 좋아보입니다 !

2021-12-22 11:53 UTC, chanwoo00106 commented on src/Components/Common/Header/index.tsx
>  import { faBars, faChevronUp } from "@fortawesome/free-solid-svg-icons";
`<FontAwesomeIcon icon={faBars} />` 이런 형식으로 사용하는 거라서 필요 없을 줄 알았습니다
import 할 때 `import * as SVG from "@fortawesome/free-solid-svg-icons";` 이런 형식으로 할까요?

2021-12-22 11:57 UTC, sunwoo0706 commented on src/Components/Common/Header/index.tsx
>  import { faBars, faChevronUp } from "@fortawesome/free-solid-svg-icons";
```suggestion
import { Bar as faBars, Arrow as faChevronUp } from "@fortawesome/free-solid-svg-icons";
```
이런식을 말씀드린겁니다.

`faChevronUp` 이 친구는 뭔지를 모르겠네요.

2021-12-22 12:00 UTC, sunwoo0706 commented on tsconfig.json
> +    "typeRoots": ["./types", "./node_modules/@types"]
디스코드에 변경건 관련해서 자세히 작성해주세요

2021-12-23 00:10 UTC, chanwoo00106 commented
- 불필요한 파일 지우기
- `console.log` 지우기
- `useSetRecoilState` 사용
- 커스텀 훅 만들기
- `/` 추가
- `ShowBanner` 를 `AtomContainer`로 옮기기
- localstorage key 값 변경
- fontawesome icon 명 변경

2021-12-23 00:21 UTC, sunwoo0706 commented on src/Atom/AtomContainer.ts
> +  key: "ShowBanner",
atom은 선언명과 key 값이 같게 쓰는게 좋겠군요.
내부 로직에서 판별하는거라 상관은 없지만 나중으로 미루면 좋지 않으니

2021-12-23 00:23 UTC, sunwoo0706 commented on src/Components/Banner/index.tsx
> +    const storage = localStorage.getItem("the-moment-banner");
`storage` 명이 일치하지 않습니다.

2021-12-23 00:23 UTC, chanwoo00106 commented on src/Components/Banner/index.tsx
> +    const storage = localStorage.getItem("the-moment-banner");
깜빡하고 바꾸지 않았네요;;

2021-12-23 00:26 UTC, chanwoo00106 commented
- atom은 선언 명과 key 값이 같게 수정
- storage 명 변경

2021-12-23 00:59 UTC, sunwoo0706 approved these changes
수고하셨습니다 *^^*

2021-12-23 01:00 UTC, yoosion030 approved these changes
수고하셨습니다

2021-12-23 01:49 UTC, hyeongrok7874 approved these changes
수고 많으셨습니다~~ 👍

2021-12-23 02:02 UTC, ImChangGyu approved these changes
수고하셨습니다

2021-12-23 04:21 UTC, merged